#Application Name
spring.application.name=Enotes_Api_Service

#Datasbase Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/test_db
spring.datasource.username=postgres
spring.datasource.password=hello

#Jpa Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#Current Profile
my.config=becoder-config

#File Upload Path
file.upload.path=/notes/

#File Upload Size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#Email Send Config
spring.mail.username=abdulrahmanpatni@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.password=figj firm aqnr pibf
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring seccurity config

#Logging Security
logging.level.org.springframework.security=debug
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=error
logging.level.org.springframework.security.web.FilterChainProxy=debug


