spring:
  application:
    name: enotes-api-service
  profiles:
    active: dev
springdoc:
  swagger-ui:
    operationsSorter: method
    tags-sorter: alpha
    path: /ENotes-doc
---
#Dev Config:
spring:
  config:
      activate:
        on-profile: dev
  datasource:
      url: jdbc:postgresql://localhost:5432/enotes_db-Dev
      username: postgres
      password: hello
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    username: abdulrahmanpatni@gmail.com
    host: smtp.gmail.com
    password: qflj repk blrz qynj
    port: 587
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
file:
  upload:
    path: /notes/
---
#test
spring:
    config:
      activate:
        on-profile: test
    datasource:
      url: jdbc:postgresql://localhost:5432/test_db
      username: postgres
      password: hello
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
    mail:
      username: abdulrahmanpatni@gmail.com
      host: smtp.gmail.com
      password: qflj repk blrz qynj
      port: 587
      properties:
        mail:
          smtp:
            auth: true
          starttls:
            enable:true
file:
  upload:
    path: /notes/

---
#Prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/prod_db
    username: postgres
    password: hello
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    username: abdulrahmanpatni@gmail.com
    host: smtp.gmail.com
    password: qflj repk blrz qynj
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:true
logging:
    level:
      org:
      springframework:
        security: debug
        web:
          FilterChainProxy: debug


file:
  upload:
    path: /notes/
