spring.application.name=Enotes_Api_Service
spring.datasource.url=jdbc:postgresql://localhost:5432/enotes_db
spring.datasource.username=postgres
spring.datasource.password=hello

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
my.config=becoder-config
spring.profiles.active=dev
