#Application Name
spring.application.name=Enotes_Api_Service

#Datasbase Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/enotes_db
spring.datasource.username=postgres
spring.datasource.password=hello

#Jpa Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Current Profile
my.config=becoder-config
spring.profiles.active=dev

#File Upload Path
file.upload.path=/notes/

#File Upload Size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB






