#Save Category
POST  http://localhost:8080/api/v1/category/save-category
Content-Type: application/json

{
  "name": "Th",
  "description": "It is a  Java Springboot",
  "isActive": true
}

####
#Get All Category
GET http://localhost:8080/api/v1/category/Category
###

#GetById

GET http://localhost:8080/api/v1/category/10
###

#DeleteCategoryById

DELETE http://localhost:8080/api/v1/category/10
###

GET http://localhost:8080/api/v1/category/active-Category

